name: passwd
description: A beautiful and secure password manager.
version: 2.0.0+2
author: Akshit Garg
publish_to: none

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  autofill_service:
    git: https://github.com/gargakshit/autofill_service
  animations: ^1.1.2
  archive: ^2.0.13
  async_redux: ^6.0.1
  barcode_scan: ^3.0.1
  base_x: ^1.0.1
  biometric_storage: ^1.1.0+1
  cached_network_image: ^2.3.3
  crypto: ^2.1.5
  cryptography: ^1.4.1
  dart_otp: ^1.3.0
  desktop_window: ^0.3.0
  dio: ^3.0.10
  encrypt: ^4.1.0
  ez_localization: ^0.3.0+1
  flutter_icons: ^1.1.0
  flutter_otp_text_field: ^0.0.1+1
  flutter_secure_storage: ^3.3.4
  functional_data: ^0.3.0
  get_it: ^5.0.1
  google_fonts: ^1.1.1
  injectable: ^1.0.5
  logging: ^0.11.4
  logging_appenders: ^0.4.3
  msgpack_dart: ^0.0.7
  path: ^1.8.0-nullsafety.1
  path_provider: ^1.6.24
  percent_indicator: ^2.1.8
  pinenacl: ^0.1.3
  provider: ^4.3.2+2
  provider_for_redux: ^1.1.3
  responsive_builder: ^0.3.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.12+4
  supercharged: ^1.11.1
  touch_bar: ^0.0.1-alpha.1
  touch_bar_macos: ^0.0.1-alpha.1
  tuple: ^1.0.3
  url_launcher: 5.7.10

dev_dependencies:
  # integration_test: ^1.0.2+2
  flutter_test:
    sdk: flutter
  # flutter_driver:
  # sdk: flutter
  build_runner: ^1.10.2
  flutter_launcher_icons: ^0.8.1
  functional_data_generator: ^0.3.7
  injectable_generator: ^1.0.5
  pedantic: ^1.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/languages/

flutter_icons:
  android: true
  ios: true
  image_path_ios: assets/icons/ios.png
  image_path_android: assets/icons/android.png
  image_path: assets/icons/ios.png
  adaptive_icon_background: assets/icons/adaptive_bg.png
  adaptive_icon_foreground: assets/icons/adaptive_fg.png
